### PR TITLE
feat: add support for decancer v3.0.1

### PR DESCRIPTION
**Pull request by null8626**
Hai! This pull request adds support for *decancer*'s latest version, which is v3.0.1. This pull request also updates the `pyo3` dependency, therefore also closing #11.

### CODE REVIEW

**Comment by Jonxslays** [comment]
Thanks @null8626 I will get this merged and released tonight after work. I think I'd like `Options` to be strongly typed rather than a dictionary. I'd also like to update the tests, but I'll take care of these changes.

**Comment by null8626** [comment]
I feel like it's more fitting to be `decancer.parse('text', retain_capitaliztion=True, pure_homoglyph=True)` or something like that... Feel free to let me know how it should go, thanks.

**Comment by Jonxslays** [comment]
i was picturing something like

```py
options = (
    Options.RETAIN_CAPITALIZATION | 
    Options.PURE_HOMOGLYPH
)

decancer.parse("text", options)
```
but frankly after typing it on mobile it feels more verbose than it needs to be. I'll just keep your kwarg implementation but make sure it's well documented the keywords it accepts. Maybe throw a runtime or value error if an invalid one is passed.

**Comment by null8626** [comment]
Sounds good!

**Pull request merged**
